# Generated by Django 3.1.4 on 2021-03-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebilog', '0006_auto_20210308_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='No snippet available for this post!', max_length=255),
        ),
    ]
